[app]
name = "leaderpro"
environment = "local"
port = "5000"

  [app.auth]
  access-token-duration = "15m"
  refresh-token-duration = "24h"
  paseto-symmetric-key = "dFRpaeCkdLuKpv65vN7QDSGm5M4H6EWe"

[cache]
  [cache.redis]
  host = "localhost" # redis container name
  port = 6379
  db = 0
  pass = "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
  default-expiration = "24h"
  
[db]
  [db.mysql]
  username = "root"
  password = "root"
  host = "localhost" # mysql container name
  port = 3306
  db-name = "leaderpro_db"
  max-life-in-minutes = 1
  max-idle-connections = 5
  max-open-connections = 100

[log]
debug = true
log-to-file = false
path = "leaderpro.log"

[ai]
default-provider = "openai"

  [ai.openai]
  api-key = ""  # Override with AI_OPENAI_API_KEY environment variable
  model = "gpt-4o-mini"
  temperature = 0.7
  max-tokens = 2000
  base-url = "https://api.openai.com/v1"

  [ai.anthropic]
  api-key = "your-anthropic-api-key-here"  # Override with AI_ANTHROPIC_API_KEY environment variable
  model = "claude-3-5-sonnet-20241022"
  temperature = 0.7
  max-tokens = 2000

  [ai.rate-limit]
  requests-per-minute = 10
  requests-per-hour = 100
  requests-per-day = 500